spring.application.name=eda-compras

spring.activemq.broker-url=vm://localhost?broker.persistent=false
spring.activemq.in-memory=true
spring.activemq.packages.trust-all=true

spring.jms.pub-sub-domain=false